# nixpacks.toml

[phases.setup]
nixPkgs = ["ffmpeg", "ffmpeg-headless", "freetype", "gcc", "libjpeg", "libpng", "libsndfile", "libsodium", "openblas", "libopus", "python3", "zeromq", "zlib"]
# Or potentially just "opus" if using a newer nixpkgs version, see Solution 2

# Add other phases (install, build, start) as needed
